### ISSUE TITLE
Lodestone Crashes Game On Start UP.

### ISSUE THREAD

**Issue by toErIpNid** [LodestarMC/Lodestone#11]
Game Ver: 1.18.2.

Mod Ver: 1.4.

Forge Ver: 40.2.1.

Log: https://pastebin.com/kWwZmjNw

**Comment by toErIpNid** [comment]
Downgrading Lodestone to a previous version fixes this issue for some reason.

**Comment by SammySemicolon** [comment]
You can't use latest malum with latest lodestone. This isn't a problem with lodestone, it's just that malum hasn't been updated to the latest version of lodestone yet.
