### ISSUE TITLE
Particles aren't showing up when using shaders.

### ISSUE THREAD

**Issue by KevinTheG0D** [LodestarMC/Lodestone#23]
When using shaders, lodestone particles don't render at all. I know that lodestone uses core shaders and shader mods need to disable them, so that they can work. but is there any way to fix that?

**Comment by SammySemicolon** [comment]
Apologies for the long delay before a response, I was and still am recovering from surgery so replying to issues wasn't my priority.
It's something I myself have to write a compatibility layer for, intertwining lodestone's deferred renderer with the rendering pipeline of whatever shader mod I'll choose.

**Comment by KevinTheG0D** [comment]
I would prefer Iris as a shader mod. But that‘s ofc your decision. Also i hope you recover soon. I also had a surgery and it sucks

**Comment by SammySemicolon** [comment]
It's most likely gonna be iris yeah
