### ISSUE TITLE
Lodestone causes crash on dev environment

### ISSUE THREAD

**Issue by QinomeD** [LodestarMC/Lodestone#4]
As in title, it just crashes. Seems like it's something with mixins (I tried `-Dmixin.env.disableRefMap=true` btw)

Latest.log
[latest.log](https://github.com/LodestarMC/Lodestone/files/9287475/latest.log)

**Comment by QinomeD** [comment]
1.0, that's the newest on cf (because I use curse maven, wanted to do it with maven now, but I just forgot)

**Comment by SammySemicolon** [comment]
1.0 is rlly old yeah, we've went through like 200-300 commits since then. Grab one of the libs from here https://maven.blamejared.com/team/lodestar/lodestone/lodestone/

**Comment by QinomeD** [comment]
Seems fair, but why is the 1.0 newest on curse then?

**Comment by SammySemicolon** [comment]
I haven't had any reason to release 1.1, seeing as the only mod to my knowledge relying on it is malum atm. We're gonna push out a jar right now.

**Comment by QinomeD** [comment]
Cool

**Comment by QinomeD** [comment]
Wait, then you have to fix Malum to use `team.lodestar.lodestone` instead of `com.sammy.ortus`

**Comment by SammySemicolon** [comment]
already done

**Comment by QinomeD** [comment]
Huh? Then it seems like I'm using an outdated version.

**Comment by SammySemicolon** [comment]
1.3 malum will be incompatible with 1.1 lodestone, but nothing I can do about that. 1.4 moved over to the new name already (all it took is two ctrl shift R replace uses)

**Comment by SammySemicolon** [comment]
https://maven.blamejared.com/com/sammy/malum/malum/1.18.2-1.4-58/ should be the one

**Comment by QinomeD** [comment]
oh cool
thanks
