### ISSUE TITLE
[1.18.2]Crash with Rubidium

### ISSUE THREAD

**Issue by SaltSouls** [LodestarMC/Lodestone#5]
### Description:
Upon killing a monster and a spirit is summoned the game crashes due to a rendering issue. I figure that this is an issue with Lodestone and not Malum as Lodestone contains all of Malums rendering code for things like the spirits.

### Versions:
- Forge: 40.1.74
- Lodestone: 1.18.2-1.1
- Malum: 1.18.2-1.4
- Rubidium: 0.5.3a

### Logs:
[Latest.log](https://gist.github.com/SaltSouls/75a987a151a89bb2d8e89828b4080d9f)
[Crash.txt](https://gist.github.com/SaltSouls/2299b77ad057d41b16fa9a94a0b16ae6)

**Comment by amoooooo** [comment]
In the lodestone client config, turn off `buffer particles`

**Comment by MrAnkylasuarus** [comment]
I have this same issue, I want to try turning off buffer particles in the lodestone client config, but there is no lodestone or malum related config in the config folder.

**Comment by SammySemicolon** [comment]
This should be fixed in modern versions of lodestone
