### ISSUE TITLE
License mismatch between CurseForge page and sources

### ISSUE THREAD

**Issue by mikerooni** [LodestarMC/Lodestone#55]
The project is marked as LGPL-licensed on its CurseForge page while the sources contain the regular GPL license.

Could you please fix whichever one of these is wrong? I know changing a license - especially if it requires obtaining the approval from contributors - can be quite tedious.  
But this is important for anyone considering to use this as a library, as it's basically impossible to determine the licensing requirements for any dependent projects otherwise.

**Comment by SammySemicolon** [comment]
Donezo, It's LGPL across github and curseforge

**Comment by mikerooni** [comment]
Oh well that was quick - thank you for resolving it!
