### ISSUE TITLE
i punch skelton and my game make error

### ISSUE THREAD

**Issue by CyberFIowey** [LodestarMC/Lodestone#6]
https://crashy.net/bEf3cthMYb1kwAE5XdYg

I hit the skeleton with a mod weapon from the mod mekanism meka tool

and after that, an error of this mod came out and I could click return to the menu, but when I decided to continue playing, I went in and saw that my camera was looking forward, but everything was somehow wrong, even my hand and everything in it not looked great

**Comment by amoooooo** [comment]
in the `lodestone-common` config file set `buffer particles` to false.

**Comment by CyberFIowey** [comment]
ok thanks

**Comment by CyberFIowey** [comment]
I've had it like this once, so it's a rare thing.

**Comment by amoooooo** [comment]
Happens with rubidium

**Comment by CyberFIowey** [comment]
ohh i understand
